### ISSUE TITLE
thread 'main' panicked at 'Failed to update QBittorrent.: HTTP status client error (405 Method Not Allowed) for url (http://127.0.0.1:8080/api/v2/app/setPreferences?json=... src/main.rs:18:55

### ISSUE THREAD

**Issue by skuizy** [fusetim/external_natpmp_qbittorrent#3]
La méthode GET n'est plus supportée pour modifier les paramètres dans les nouvelles versions de qBittorrent : https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#general-information

**Comment by fusetim** [comment]
Image avec la correction disponible : [v0.1.1](https://github.com/fusetim/external_natpmp_qbittorrent/pkgs/container/external_natpmp_qbittorrent/118132919?tag=v0.1.1)
