### ISSUE TITLE
thread 'main' panicked at 'Failed to update QBittorrent.: HTTP status client error (400 Bad Request)

### ISSUE THREAD

**Issue by JeffFaer** [fusetim/external_natpmp_qbittorrent#4]
```sh
$ qbittorrent-nox --version
qBittorrent v4.5.5
```

I was originally getting 403s, so I disabled auth for requests coming from localhost. Then I started getting

> thread 'main' panicked at 'Failed to update QBittorrent.: HTTP status client error (400 Bad Request) for url (http://127.0.0.1:8080/api/v2/app/setPreferences?json=%7B%22listen_port%22%3A63148%7D)', src/main.rs:17:55

I found some threads ([1](https://github.com/qbittorrent/qBittorrent/issues/10975), [2](https://github.com/qbittorrent/qBittorrent/issues/18097)) on the qbittorrent github page about unexpected 400s and tried some of the stuff there.

Sending the `json={"listen_port": 63148}` as HTTP data instead of a URL param seemed to do the trick

**Comment by fusetim** [comment]
Ah yes, you surely have found the correct fix. I did not tested the latest update on Qbittorrent ^4.5.

A fix will be provided soon. Thanks for your detailed bug report.

**Comment by fusetim** [comment]
Issue should be fixed with this new version, try: 
[`ghcr.io/fusetim/external_natpmp_qbittorrent:ecf567b21e5f079762e36c9cee9afaf86fcb22be`](https://github.com/fusetim/external_natpmp_qbittorrent/pkgs/container/external_natpmp_qbittorrent/124412439?tag=ecf567b21e5f079762e36c9cee9afaf86fcb22be)
